export const busRoutes = [
    {
        id: 1,
        name: "Tuyến xe số 1",
        start: "Trường ĐH KHTN",
        end: "Chợ Bến Thành",
        distance: "10km",
        status: "active",
        startTime: "6:00",
        endTime: "10:00",
    },
    {
        id: 2,
        name: "Tuyến xe số 2",
        start: "Trường ĐH KHTN",
        end: "Mỹ Tho",
        distance: "15km",
        status: "inactive",
        startTime: "3:00",
        endTime: "9:00",
    },
    {
        id: 3,
        name: "Tuyến xe số 3",
        start: "Trường Back Khoa",
        end: "Chợ Bến Thành",
        distance: "10km",
        status: "inactive",
        startTime: "7:00",
        endTime: "9:00",
    },
    {
        id: 4,
        name: "Tuyến xe số 4",
        start: "Trường ĐH KHTN",
        end: "Chợ Bến Thành",
        distance: "10km",
        status: "inactive",
        startTime: "7:00",
        endTime: "9:00",
    },
    {
        id: 5,
        name: "Tuyến xe số 5",
        start: "Trường ĐH KHTN",
        end: "Chợ Bến Thành",
        distance: "10km",
        status: "inactive",
        startTime: "7:00",
        endTime: "9:00",
    },
    {
        id: 6,
        name: "Tuyến xe số 6",
        start: "Trường ĐH KHTN",
        end: "Chợ Bến Thành",
        distance: "10km",
        status: "inactive",
        startTime: "7:00",
        endTime: "9:00",
    },
    {
        id: 7,
        name: "Tuyến xe số 7",
        start: "Trường ĐH KHTN",
        end: "Chợ Bến Thành",
        distance: "10km",
        status: "inactive",
        startTime: "7:00",
        endTime: "9:00",
    },
    {
        id: 8,
        name: "Tuyến xe số 8",
        start: "Trường ĐH KHTN",
        end: "Chợ Bến Thành",
        distance: "10km",
        status: "inactive",
        startTime: "7:00",
        endTime: "9:00",
    },
]